services:
  node:
    build:
      context: node
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000

  postgres:
    env_file:
      - .env
    hostname: postgres
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
