apiVersion: v1
kind: Pod
metadata:
  name: ideal-train
  labels:
    name: ideal-train
spec:
  containers:
    - name: ideal-train
      image: mariusraupach/ideal-train
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  containers:
    - name: postgres
      image: postgres:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 5432
