apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-node"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-node"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-node"
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              while ! nc -z "{{ .Release.Name }}-postgres" 5432; do
                sleep 2
              done
      containers:
        - name: "{{ .Release.Name }}-node"
          image: "mariusraupach/chromie:{{ .Values.node.image.tag }}"
          resources:
            limits:
              memory: "{{ .Values.node.resources.limits.memory }}"
              cpu: "{{ .Values.node.resources.limits.cpu }}"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}"
            - secretRef:
                name: "{{ .Release.Name }}"
          imagePullPolicy: Always
