services:
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ..:/workspaces/ideal-train

  postgres:
    env_file:
      - .env
    hostname: postgres
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
