import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Providers from "@/components/providers";
import { cn } from "@/lib/utils";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "chronos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("text-xs antialiased", inter.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
