apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromie
spec:
  selector:
    matchLabels:
      app: chromie
  template:
    metadata:
      labels:
        app: chromie
    spec:
      containers:
        - name: chromie
          image: mariusraupach/chromie:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: user
            - name: TZ
              value: Europe/Berlin
---
apiVersion: v1
kind: Service
metadata:
  name: chromie
spec:
  selector:
    app: chromie
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
