apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-postgres"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-postgres"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-postgres"
    spec:
      containers:
        - name: "{{ .Release.Name }}-postgres"
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          resources:
            limits:
              memory: "{{ .Values.postgres.resources.limits.memory }}"
              cpu: "{{ .Values.postgres.resources.limits.cpu }}"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}"
            - secretRef:
                name: "{{ .Release.Name }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: "{{ .Release.Name }}-postgres-data"
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: "{{ .Release.Name }}-postgres-data"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-postgres-data"
